micronaut:
  application:
    name: refactor
datasources:
  default:
    url: jdbc:h2:~/refactor.db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driverClassName: org.h2.Driver
jpa:
  default:
    packages-to-scan:
      - 'id.diasna.refactor.adapter.repository'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true